version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "22:25"
      timezone: "Asia/Tokyo"
      versioning-strategy: "lockfile-only"
