version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "23:26"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "23:26"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    
