version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:32"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 2
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:32"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 2
    
    
